CREATE TABLE CHEONANSTATION (
  PNO      INTEGER      NOT NULL COMMENT '기차일련번호', -- 기차일련번호
  STARTTIME    TIME NOT NULL COMMENT '기차출발시간', -- 버스출발시간
  ARRIVALTIME    TIME NOT NULL COMMENT '기차도착시간', -- 기차도착시간
  ROUTENAME  VARCHAR(100) NOT NULL COMMENT '노선명' -- 노선명
)
COMMENT '천안역';

-- 상품목록
ALTER TABLE CHEONANSTATION
  ADD CONSTRAINT PK_CHEONANSTATION -- 천안역 기본키
    PRIMARY KEY (
      PNO -- 기차일련번호
    );

ALTER TABLE CHEONANSTATION
  MODIFY COLUMN PNO INTEGER NOT NULL AUTO_INCREMENT COMMENT '기차일련번호';
  
INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('05:00','07:30','광운대(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('05:30','08:00','광운대(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('06:12','08:42','광운대(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('06:26','08:56','광운대(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('06:50','09:20','광운대(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('21:29','23:59','광운대(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('05:16','07:36','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('05:39','07:59','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('07:05','09:25','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('08:23','10:43','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('09:03','10:23','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('10:02','12:22','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('11:01','13:21','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('12:19','14:39','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('13:03','15:23','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('14:21','16:41','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('15:01','17:21','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('16:11','18:31','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('17:14','19:34','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('18:00','19:20','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('19:06','21:36','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('20:07','22:37','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('21:06','23:26','청량리(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('08:29','09:20','병점(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('09:11','10:01','병점(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('13:12','14:02','병점(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('20:42','21:32','병점(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('22:17','23:07','병점(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('23:10','24:00','병점(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('23:31','24:20','병점(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('21:49','23:30','구로(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('22:06','23:46','구로(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('22:31','24:11','구로(상행)');

INSERT INTO CHEONANSTATION(STARTTIME, ARRIVALTIME,ROUTENAME)
VALUES ('22:50','24:31','구로(상행)');

