CREATE TABLE HOSEOSHUTTLE (
  NUMBEROFSERVICE INT NOT NULL COMMENT '운행횟수', -- 운행횟수
  CHEONANSTART    TIME  NULL COMMENT '천캠출발', -- 천캠출발
  CHEONANTERMINAL    TIME  NULL COMMENT '천안터미널', -- 천안터미널
  CHEONANSTATION TIME  NULL COMMENT '천안역', -- 천안역
  CHUNGMU TIME NULL COMMENT '충무병원', -- 충무병원
  SSANGYOUNG TIME NULL COMMENT '쌍용3동', -- 쌍용3동
  ASANSTATION TIME NULL COMMENT '천안아산역', -- 천안아산역
  ASANCAM TIME NULL COMMENT '아캠도착' -- 아캠도착
)
COMMENT '호서셔틀';

-- 상품목록
ALTER TABLE HOSEOSHUTTLE
  ADD CONSTRAINT PK_HOSEOSHUTTLE -- 호서셔틀 기본키
    PRIMARY KEY (
      NUMBEROFSERVICE -- 운행횟수
    );

ALTER TABLE HOSEOSHUTTLE
  MODIFY COLUMN NUMBEROFSERVICE INTEGER NOT NULL AUTO_INCREMENT COMMENT '운행횟수';